name: Test

on:
  workflow_dispatch:
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [win64,winarm64,linux64,linuxarm64]
        variant: [nonfree-shared,nonfree-shared 8.0,nonfree-shared 7.1,nonfree-shared 6.1,nonfree,nonfree 8.0,nonfree 7.1,nonfree 6.1]
    steps:
      - name: Test
        run: |
          VARIANT="${{ matrix.variant }}"
          PREFIX="${VARIANT%% *}"
          SLUG="${{ matrix.target }}-${PREFIX// /-}"
          echo "artifact_slug=${SLUG// /-}" >> $GITHUB_OUTPUT
          echo "Generated: ${SLUG}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
